#!/bin/bash

#SBATCH --account=def-mgoubran
#SBATCH --time=0:14:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=48G
#SBATCH --array=1-1%1
#SBATCH --output=slurm_%x_%j.out

export BRAINLAB_DIR=${HOME}/work/code/brainlab
export BLT_CONTAINER_DIR=${SCRATCH}/containers/current

idx=$SLURM_ARRAY_TASK_ID
${BRAINLAB_DIR}/dataset-runners/testing/hfb/run_icvmapper ${idx}
