#!/bin/bash
# ------------------------------------------------------------------------------
### PROCESSING NOTES (CEDAR) ###
#  - BEAM:   6 cores: ~01:40:00 @ 9 GB
#  - ONDRI:  6 cores: ~01:09:00 @ 8 GB
#  - LEDUCQ: 8 cores: ?
#-------------------------------------------------------------------------------

#SBATCH --account=def-mgoubran
#SBATCH --time=11:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --output=slurm_%x_%A_%a.out
#SBATCH --array=5-5%1

# ------------------------------------------------------------------------------
### SETUP ###
#-------------------------------------------------------------------------------

threads=8

list_fn="${SCRATCH}/subject_list_1.txt"
in_dir="${SCRATCH}/dti_test/organized"
out_dir="${SCRATCH}/dti_test/derivatives/dti"
scratch_dir="${SCRATCH}/junk"
alps_roi_dir="${SCRATCH}/shared/resources/alps-rois"
dry_run=0
regrid_size="1,1,1" 
dwi_pfx="*"
dry_run=0
cleanup=0


BRAINLAB_DIR=${HOME}/work/code/brainlab

# ------------------------------------------------------------------------------
### JOB ###
#-------------------------------------------------------------------------------
IDX=${SLURM_ARRAY_TASK_ID}
#-------------------------------------------------------------------------------

sub_id=$(sed -n "${IDX}p" ${list_fn})

${BRAINLAB_DIR}/wrapper-scripts/bash/blt_dwi_preprocess \
  --in_dir "${in_dir}" \
  --out_dir "${out_dir}" \
  --scratch_dir_root "${scratch_dir}" \
  --alps_roi_dir "${alps_roi_dir}" \
  --threads "${threads}" \
  --dry_run "${dry_run}" \
  --sub_id "${sub_id}" \
  --dwi_pfx "${dwi_pfx}" \
  --regrid_size "${regrid_size}" \
  --cleanup "${cleanup}"

# ------------------------------------------------------------------------------
